import { createActions } from 'redux-actions';

const {
  getItems,
  getItemsSucceed,
  getItemsFailed,
  deleteItem,
  deleteItemSucceed,
  deleteItemFailed,
  updateItem,
  updateItemSucceed,
  updateItemFailed,
  deleteItem1,
  deleteItem1Succeed,
  deleteItem1Failed,
  addItem,
  addItemSucceed,
  addItemFailed,
  addItem1,
  addItem1Succeed,
  addItem1Failed,
  getItem,
  getItemSucceed,
  getItemFailed,
  updateCurrentItem,
  addItems,
  addItemsSucceed,
  addItemsFailed,
  addItems1,
  addItems1Succeed,
  addItems1Failed
} = createActions({
  GET_ITEMS: params => ({ params }),
  GET_ITEMS_SUCCEED: items => ({ items }),
  GET_ITEMS_FAILED: error => ({ error }),
  DELETE_ITEM: (id, params = null) => ({ id, params }),
  DELETE_ITEM_SUCCEED: () => ({}),
  DELETE_ITEM_FAILED: error => ({ error }),
  DELETE_ITEM_1: (id, params = null) => ({ id, params }),
  DELETE_ITEM_1_SUCCEED: () => ({}),
  DELETE_ITEM_1_FAILED: error => ({ error }),
  UPDATE_ITEM: ({ id, item, params = null }) => ({ id, item, params }),
  UPDATE_ITEM_SUCCEED: () => ({}),
  UPDATE_ITEM_FAILED: error => ({ error }),
  ADD_ITEM: (item, params = null) => ({ item, params }),
  ADD_ITEM_SUCCEED: () => ({}),
  ADD_ITEM_FAILED: error => ({ error }),
  ADD_ITEM_1: (item, params = null) => ({ item, params }),
  ADD_ITEM__1_SUCCEED: () => ({}),
  ADD_ITEM_1_FAILED: error => ({ error }),
  GET_ITEM: id => ({ id }),
  GET_ITEM_SUCCEED: item => ({ item }),
  GET_ITEM_FAILED: error => ({ error }),
  UPDATE_CURRENT_ITEM: item => ({ item }),
  ADD_ITEMS: (items, params = null) => ({ items, params }),
  ADD_ITEMS_SUCCEED: () => ({}),
  ADD_ITEMS_FAILED: error => ({ error }),
  ADD_ITEMS_1: (data, params = null) => ({ data, params }),
  ADD_ITEMS_1_SUCCEED: () => ({}),
  ADD_ITEMS_1_FAILED: error => ({ error })
});

export {
  getItems,
  getItemsSucceed,
  deleteItem,
  getItemsFailed,
  deleteItemSucceed,
  deleteItemFailed,
  updateItem,
  updateItemSucceed,
  updateItemFailed,
  deleteItem1,
  deleteItem1Succeed,
  deleteItem1Failed,
  addItem,
  addItemSucceed,
  addItemFailed,
  addItem1,
  addItem1Succeed,
  addItem1Failed,
  getItem,
  getItemSucceed,
  getItemFailed,
  updateCurrentItem,
  addItems,
  addItemsFailed,
  addItemsSucceed,
  addItems1,
  addItems1Succeed,
  addItems1Failed
};
